spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fbcrunning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: fbcrunning
    password: fbcrunning
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
